# base image
FROM node:16-alpine
RUN npm config set strict-ssl false

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY ../backend/package.json /app/package.json

RUN npm install
COPY ../backend .
EXPOSE 3001

# start app
CMD ["nodemon", "server.js"]